### ISSUE TITLE
응용 어플리케이션 개발을 통한 브랜딩 전략에 대한 논의

### ISSUE THREAD

**Issue by ssaru** [DeepBaksuVision/README#2]
진우님께서, Object Detection 구현 별도로 외부 홍보를 위한다면  응용어플리케이션을 이용한 것이 더 좋을 수 있다는 피드백을 받았습니다.

해당 내용에 대해서 재원님과 찬희님 피드백을 받아보고 싶습니다.

(추후 모두콘, 백수콘, 기타 발표시)

**Comment by chjeong530** [comment]
> 네! 응용어플리케이션을 개발 하게된다면 어떤 방식의 응용 어플리케이션을 제작하는게 좋을지 논의해보고싶습니다.
> 
> 그리고 만약에 하게됬을 때, Distillation이나 네트워크 경량화 기법을 적용해서 임베디드나 이런쪽으로 내리면 더 효과가 증폭될거라는 피드백도 있었는데, 이에대해선 어떻게 생각하시나요
> 
> 해당 내용에 관해서는 찬희님이나 재원님께서 아이디어를 주시면 좋을 거 같습니다.
> 업무나 앞으로 하고싶은 업무방향으로 어필하기 좋은 어플리케이션을 적용해보고 개발해보시면 더 좋을거 같아서요.
> 
> 홍보나 발표하게 되는 경우에도 제가 나서는 방향이 아니라 멤버분들이 발표해주셨으면 합니다.

임베디드 쪽으로 올리면 좋죠. 추후 앱쪽으로 개발도 가능할거고. 
일단 제 생각으론 일단은 경량화는 추후 문제라고 생각됩니다. 
현재 어디까지 개발이 되어있는지 제가 다 파악하지 못해서요..ㅠㅠ (물론 고려하면서 개발하면 좋을 것 같긴 하구요.)
홍보나 발표하는 부분은 기회가 된다면 제가 해도 좋을 것 같습니다.

**Comment by ssaru** [comment]
아직은 YOLO 밖에 없습니다.
이제 마무리되는 단계이구요.

퍼포먼스 향상을 위해서 YOLOv3까지 확장 후에 응용어플리케이션을 개발해야하나 고민중입니다.

Pytorch 기반으로 구성되어있어서 
임베디드로 내리면 caffe로 전환해서 내려야하는 방향이 맞지않나 싶습니다.
(재원님 말씀으로는 레퍼런스가 거의 없다고 합니다.)

이제 응용어플리케이션의 주제에 대해서 결정해봐야할 것 같습니다.

발표자를 결정하는 것은 재원님도 취업시즌이셔서 미팅때 한번 논의 후에 적절한 분배를 해야할 것 같습니다. 

한번 논의해보시죠.

**Comment by insurgent92** [comment]
응용 어플리케이션이라 하면
실제 적용해볼 수 있는 프로젝트를 말씀하시는거죠?

**Comment by ssaru** [comment]
네. 서연님의 파킨슨 프로젝트와 같이 단순히 알고리즘 응용을 하는 것이 아니라 실제 적용할 수 있는 시스템을 구현하는 것을 의미합니다.

몇몇분의 피드백으로는 단순한 구현은 임팩트가 약하므로, 발표 및 브랜딩을 할 때에는 응용 어플리케이션을 만들어서 이야기하는게 좋다라는 피드백을 받았습니다.
