### ISSUE TITLE
한 Sprint당 작업할 수 있는 스토리 포인트 제한의 건

### ISSUE THREAD

**Issue by ssaru** [DeepBaksuVision/README#3]
이번에 부득이하게 대회를 진행하면서 무리한 스켸쥴 일정을 잡은 감이 있습니다.

따라서 인당 가용 스토리 포인트를 잡아놓고 해당 스토리 포인트를 초과하지 않는 선에서 Issue 할당을 진행하는 것에 대해서 의논해봤으면 좋겠습니다.

**Comment by insurgent92** [comment]
스토리 포인트가 무엇인가요?

**Comment by insurgent92** [comment]
@ssaru 좋습니다!

**Comment by ssaru** [comment]
스프린트 (7일) 기준으로 미팅 일수 제외 6일
반감해서 실 작업일 수는 3일
하루에 스토리 포인트 3으로 계산하여
한 스프린트(1주일 기준) 총 9 스토리 포인트를 사용
